import type { Layer, Zone, CriterionRow, SuitMeta, SuitClass } from './types';

export const SUIT_META: Record<SuitClass, SuitMeta> = {
  'very-high': { label: 'Very High',  color: '#00c896', bg: 'rgba(0,200,150,0.18)',  range: '4.20–5.00', textColor: '#00c896' },
  'high':      { label: 'High',       color: '#4ade80', bg: 'rgba(74,222,128,0.15)', range: '3.40–4.20', textColor: '#4ade80' },
  'moderate':  { label: 'Moderate',   color: '#fbbf24', bg: 'rgba(251,191,36,0.15)', range: '2.60–3.40', textColor: '#fbbf24' },
  'low':       { label: 'Low',        color: '#f97316', bg: 'rgba(249,115,22,0.15)', range: '1.80–2.60', textColor: '#f97316' },
  'very-low':  { label: 'Very Low',   color: '#ef4444', bg: 'rgba(239,68,68,0.14)',  range: '1.00–1.80', textColor: '#ef4444' },
};

export const SUIT_ORDER: SuitClass[] = ['very-high', 'high', 'moderate', 'low', 'very-low'];

export function scoreToClass(score: number | null): SuitClass {
  if (score === null || isNaN(score)) return 'very-low';
  if (score >= 4.2) return 'very-high';
  if (score >= 3.4) return 'high';
  if (score >= 2.6) return 'moderate';
  if (score >= 1.8) return 'low';
  return 'very-low';
}

export function classValueToSuitClass(val: number | null): SuitClass {
  switch (val) {
    case 5: return 'very-high';
    case 4: return 'high';
    case 3: return 'moderate';
    case 2: return 'low';
    case 1:
    default: return 'very-low';
  }
}

export const HIMACHAL_LOCATIONS = [
  { name: 'Shimla', lat: 31.1048, lng: 77.1734, district: 'Shimla' },
  { name: 'Kullu', lat: 31.9579, lng: 77.1095, district: 'Kullu' },
  { name: 'Manali', lat: 32.2432, lng: 77.1892, district: 'Kullu' },
  { name: 'Dharamshala', lat: 32.2190, lng: 76.3234, district: 'Kangra' },
  { name: 'Mandi', lat: 31.7087, lng: 76.9320, district: 'Mandi' },
  { name: 'Solan', lat: 30.9045, lng: 77.0967, district: 'Solan' },
  { name: 'Bilaspur', lat: 31.3260, lng: 76.7570, district: 'Bilaspur' },
  { name: 'Hamirpur', lat: 31.6862, lng: 76.5213, district: 'Hamirpur' },
  { name: 'Una', lat: 31.4685, lng: 76.2708, district: 'Una' },
  { name: 'Chamba', lat: 32.5534, lng: 76.1258, district: 'Chamba' },
];

export const CRITERIA_INFO: Record<string, { label: string; group: Layer['group']; groupLabel: string; unit: string; source: string; description: string; evidence: string }> = {
  rainfall: {
    label: 'Annual Rainfall',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    unit: 'mm/yr',
    source: 'CHIRPS v2.0 (UCSB / IMD)',
    description: 'Mean annual precipitation across Himachal Pradesh. Heavy monsoonal precipitation elevates flood risk.',
    evidence: 'High precipitation intensity directly increases peak overland flow and catchment discharge.',
  },
  distance_to_rivers: {
    label: 'Distance to Rivers',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    unit: 'm',
    source: 'HydroRIVERS / OpenStreetMap',
    description: 'Euclidean distance to perennial river channels (Beas, Satluj, Ravi, Chenab, Yamuna basins).',
    evidence: 'Proximity to river corridors (<500 m) exhibits the highest susceptibility to overbank spilling and flash floods.',
  },
  drainage_density: {
    label: 'Drainage Density',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    unit: 'km/km²',
    source: 'Stream Network Analysis',
    description: 'Total stream length per unit basin area, reflecting catchment dissection and runoff efficiency.',
    evidence: 'High drainage density correlates with rapid catchment response times during extreme weather events.',
  },
  flow_accumulation: {
    label: 'Flow Accumulation',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    unit: 'cells',
    source: 'SRTM D8 Flow Routing',
    description: 'Cumulative upstream contributing area for each 30 m cell across Himalayan drainage basins.',
    evidence: 'High flow accumulation delineates primary drainage paths where floodwaters rapidly converge.',
  },
  twi: {
    label: 'Topographic Wetness Index (TWI)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    unit: 'index',
    source: 'DEM Second Derivatives (ln(a/tanβ))',
    description: 'Topographic Wetness Index quantifying topographic control on hydrological processes.',
    evidence: 'High TWI identifies zones of persistent soil saturation and surface ponding potential.',
  },
  elevation: {
    label: 'Elevation',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    unit: 'm asl',
    source: 'SRTM 30 m DEM',
    description: 'Digital elevation model representing terrain height from 300 m (plains) to >6,000 m (Himalayan peaks).',
    evidence: 'Low-elevation valley bottoms and floodplain terraces represent prime flood inundation zones.',
  },
  slope: {
    label: 'Terrain Slope',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    unit: '°',
    source: 'SRTM 30 m DEM',
    description: 'Surface slope gradient. Flat and low-slope valley bottoms accumulate runoff, creating severe flood inundation.',
    evidence: 'Low slopes (0–5°) impede runoff egress, concentrating water in vulnerable valley floors.',
  },
  curvature: {
    label: 'Profile/Plan Curvature',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    unit: '1/m',
    source: 'SRTM DEM Derivatives',
    description: 'Surface curvature indicating flow convergence (concave) or flow divergence (convex).',
    evidence: 'Concave terrain shapes channel runoff inward, heightening localized flood depth.',
  },
  lulc: {
    label: 'Land Use / Land Cover (LULC)',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    unit: 'class',
    source: 'ESA WorldCover 10 m / Sentinel-2',
    description: 'Land use and land cover classes including built-up, agriculture, dense forest, water bodies, and snow.',
    evidence: 'Impervious urban surfaces and bare soil generate rapid surface runoff compared to forested catchments.',
  },
  soil: {
    label: 'Soil Texture & Permeability',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    unit: 'class',
    source: 'SoilGrids v2.0 (ISRIC 250 m)',
    description: 'Soil textural classes and hydraulic conductivity controlling infiltration capacity.',
    evidence: 'Clayey and compacted soils reduce infiltration rates, transforming rainfall directly into surface runoff.',
  },
  ndvi: {
    label: 'NDVI (Vegetation Density)',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    unit: 'index',
    source: 'Sentinel-2 L2A Annual Composite',
    description: 'Normalised Difference Vegetation Index measuring live green vegetation canopy.',
    evidence: 'Dense vegetation canopy mitigates raindrop impact and promotes rainfall interception.',
  },
};

// Canonical 28 published rasters (matching Run #56)
export const INITIAL_LAYERS: Layer[] = [
  // ── Results ──
  {
    id: 'flood_11_factor_v1_available_evidence_suitability_classified',
    name: 'Flood Suitability — Classified',
    group: 'composite',
    groupLabel: 'Analysis Results',
    subgroup: 'Analysis Results',
    layerType: 'RESULT',
    visible: true,
    opacity: 85,
    unit: 'class (1–5)',
    source: 'AHP Multi-Criteria Composite (Run #56)',
    resolution: '30 m',
    date: '2026-09',
    description: 'Canonical user-facing classified flood susceptibility (1: Very Low to 5: Very High) with Available-Evidence Renormalization.',
  },
  {
    id: 'flood_11_factor_v1_available_evidence_suitability',
    name: 'Flood Suitability — Continuous',
    group: 'composite',
    groupLabel: 'Analysis Results',
    subgroup: 'Analysis Results',
    layerType: 'RESULT',
    visible: false,
    opacity: 80,
    unit: 'score (1.0–5.0)',
    source: 'AHP Multi-Criteria Composite (Run #56)',
    resolution: '30 m',
    date: '2026-09',
    description: 'Canonical continuous flood suitability score (1.0 to 5.0) under Available-Evidence mode.',
  },
  {
    id: 'flood_11_factor_v1_strict_suitability_classified',
    name: 'Strict Suitability — Classified',
    group: 'composite',
    groupLabel: 'Analysis Results',
    subgroup: 'Analysis Results',
    layerType: 'RESULT',
    visible: false,
    opacity: 80,
    unit: 'class (1–5)',
    source: 'AHP Strict 11-of-11 Audit',
    resolution: '30 m',
    date: '2026-09',
    description: 'Audit product requiring all 11 criteria present without any missing data.',
  },
  {
    id: 'flood_11_factor_v1_strict_suitability',
    name: 'Strict Suitability — Continuous',
    group: 'composite',
    groupLabel: 'Analysis Results',
    subgroup: 'Analysis Results',
    layerType: 'RESULT',
    visible: false,
    opacity: 80,
    unit: 'score (1.0–5.0)',
    source: 'AHP Strict 11-of-11 Audit',
    resolution: '30 m',
    date: '2026-09',
    description: 'Strict continuous flood index (NoData wherever any criterion is missing).',
  },

  // ── Hydrological Criteria (Raw) ──
  {
    id: 'rainfall',
    name: 'Rainfall — Raw',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'HYDROLOGICAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'mm/yr',
    source: 'CHIRPS v2.0 (IMD / UCSB)',
    resolution: '30 m',
    date: '2026',
    description: 'Mean annual precipitation raster.',
  },
  {
    id: 'distance_to_rivers',
    name: 'Distance to Rivers — Raw',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'HYDROLOGICAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'm',
    source: 'HydroRIVERS / OSM',
    resolution: '30 m',
    date: '2026',
    description: 'Euclidean distance to perennial river channels.',
  },
  {
    id: 'drainage_density',
    name: 'Drainage Density — Raw',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'HYDROLOGICAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'km/km²',
    source: 'Stream Network',
    resolution: '30 m',
    date: '2026',
    description: 'Drainage network length density.',
  },
  {
    id: 'flow_accumulation',
    name: 'Flow Accumulation — Raw',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'HYDROLOGICAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'cells',
    source: 'SRTM D8',
    resolution: '30 m',
    date: '2026',
    description: 'Upstream contributing drainage area.',
  },
  {
    id: 'twi',
    name: 'TWI — Raw',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'HYDROLOGICAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'index',
    source: 'DEM Derivatives',
    resolution: '30 m',
    date: '2026',
    description: 'Topographic Wetness Index moisture retention.',
  },

  // ── Hydrological Standardized Ratings ──
  {
    id: 'rainfall_rating',
    name: 'Rainfall — Rating (1–5)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized rainfall score (1: <1000 mm to 5: >1800 mm).',
  },
  {
    id: 'distance_to_rivers_rating',
    name: 'Distance to Rivers — Rating (1–5)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized river proximity score (5: Immediate bank to 1: Far).',
  },
  {
    id: 'drainage_density_rating',
    name: 'Drainage Density — Rating (1–5)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized drainage density score (1–5).',
  },
  {
    id: 'flow_accumulation_rating',
    name: 'Flow Accumulation — Rating (1–5)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized flow accumulation score (1: Ridge to 5: Mainstem channel).',
  },
  {
    id: 'twi_rating',
    name: 'TWI — Rating (1–5)',
    group: 'hydrological',
    groupLabel: 'Hydrological Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized TWI score (1–5).',
  },

  // ── Topographic Criteria (Raw) ──
  {
    id: 'elevation',
    name: 'Elevation — Raw',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'TOPOGRAPHIC CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'm asl',
    source: 'SRTM 30 m DEM',
    resolution: '30 m',
    date: '2026',
    description: 'Digital elevation model.',
  },
  {
    id: 'slope',
    name: 'Slope — Raw',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'TOPOGRAPHIC CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: '°',
    source: 'SRTM 30 m DEM',
    resolution: '30 m',
    date: '2026',
    description: 'Terrain slope gradient.',
  },
  {
    id: 'curvature',
    name: 'Curvature — Raw',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'TOPOGRAPHIC CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: '1/m',
    source: 'SRTM DEM Derivatives',
    resolution: '30 m',
    date: '2026',
    description: 'Surface curvature.',
  },

  // ── Topographic Standardized Ratings ──
  {
    id: 'elevation_rating',
    name: 'Elevation — Rating (1–5)',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized elevation score (5: Low valley floodplains to 1: High mountains).',
  },
  {
    id: 'slope_rating',
    name: 'Slope — Rating (1–5)',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized slope score (5: Flat valley floor 0–5° to 1: Steep cliff >35°).',
  },
  {
    id: 'curvature_rating',
    name: 'Curvature — Rating (1–5)',
    group: 'topographic',
    groupLabel: 'Topographic Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized curvature score (5: Concave depression to 1: Convex ridge).',
  },

  // ── Environmental Criteria (Raw) ──
  {
    id: 'lulc',
    name: 'LULC — Raw',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'ENVIRONMENTAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'class',
    source: 'ESA WorldCover 10 m',
    resolution: '30 m',
    date: '2026',
    description: 'Land Use / Land Cover classification classes.',
  },
  {
    id: 'soil',
    name: 'Soil — Raw',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'ENVIRONMENTAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'class',
    source: 'SoilGrids v2.0 (ISRIC 250 m)',
    resolution: '30 m',
    date: '2026',
    description: 'Soil textural classes and infiltration properties.',
  },
  {
    id: 'ndvi',
    name: 'NDVI — Raw',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'ENVIRONMENTAL CRITERIA',
    layerType: 'FACTOR',
    visible: false,
    opacity: 75,
    unit: 'index',
    source: 'Sentinel-2 L2A',
    resolution: '30 m',
    date: '2026',
    description: 'Normalised Difference Vegetation Index.',
  },

  // ── Environmental Standardized Ratings ──
  {
    id: 'lulc_rating',
    name: 'LULC — Rating (1–5)',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized LULC score (5: Built-up/Water to 1: Dense Forest).',
  },
  {
    id: 'soil_rating',
    name: 'Soil — Rating (1–5)',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized soil infiltration score (5: Impervious clay to 1: Well-drained sand).',
  },
  {
    id: 'ndvi_rating',
    name: 'NDVI — Rating (1–5)',
    group: 'environmental',
    groupLabel: 'Environmental Criteria',
    subgroup: 'STANDARDIZED RATINGS',
    layerType: 'RATING',
    visible: false,
    opacity: 75,
    unit: 'rating (1–5)',
    source: 'AHP Standardized Rating (1–5)',
    resolution: '30 m',
    date: '2026',
    description: 'Standardized NDVI vegetation score (5: Sparse vegetation to 1: Dense canopy).',
  },

  // ── Quality & Coverage ──
  {
    id: 'flood_11_factor_v1_valid_criteria_count',
    name: 'Evidence Coverage',
    group: 'quality',
    groupLabel: 'Quality & Coverage',
    subgroup: 'QUALITY & COVERAGE',
    layerType: 'QUALITY',
    visible: false,
    opacity: 80,
    unit: 'criteria count (8–11)',
    source: 'Quality Control Mask',
    resolution: '30 m',
    date: '2026',
    description: 'Valid criteria count raster (8 to 11 criteria present per pixel).',
  },
  {
    id: 'flood_11_factor_v1_missing_criteria_bitmask',
    name: 'Missing Criteria',
    group: 'quality',
    groupLabel: 'Quality & Coverage',
    subgroup: 'QUALITY & COVERAGE',
    layerType: 'QUALITY',
    visible: false,
    opacity: 80,
    unit: 'bitmask',
    source: 'Quality Control Bitmask',
    resolution: '30 m',
    date: '2026',
    description: 'Bitmask raster encoding valid/missing status per criterion (2047: all valid).',
  },
];

export const INITIAL_ZONE: Zone = {
  id: 'point-himachal-sample',
  label: 'Shimla Ridge Point',
  cls: 'very-low',
  score: 1.78,
  classifiedValue: 1,
  lat: 31.8645,
  lng: 76.7920,
  district: 'Mandi / Shimla',
  region: 'Himachal Pradesh',
  area: 44.3,
  finalStatus: 'VALID',
  evidenceCount: 11,
  evidenceTotal: 11,
  missingCriteria: [],
  scoringMode: 'STRICT_11_OF_11',
  strictScore: 1.78,
  availableEvidenceScore: 1.78,
};

export const INITIAL_CRITERIA: CriterionRow[] = [
  { name: 'Terrain Slope', criterionId: 'slope', weight: 0.2306, rawScore: 28.5, rating: 1.0, contribution: 0.2306, unit: '°', cls: 'positive', layerId: 'slope', source: 'SRTM 30 m DEM', evidence: 'Steep hill slopes promote rapid surface drainage into valleys.' },
  { name: 'Distance to Rivers', criterionId: 'distance_to_rivers', weight: 0.1480, rawScore: 1850.0, rating: 1.0, contribution: 0.1480, unit: 'm', cls: 'positive', layerId: 'distance_to_rivers', source: 'HydroRIVERS', evidence: 'Located 1.85 km from primary channel, well above normal floodline.' },
  { name: 'Topographic Wetness Index', criterionId: 'twi', weight: 0.1422, rawScore: 6.2, rating: 1.0, contribution: 0.1422, unit: 'index', cls: 'positive', layerId: 'twi', source: 'SRTM D8', evidence: 'Low TWI indicates low moisture retention risk.' },
  { name: 'Annual Rainfall', criterionId: 'rainfall', weight: 0.1326, rawScore: 1420.0, rating: 4.0, contribution: 0.5304, unit: 'mm/yr', cls: 'limiting', layerId: 'rainfall', source: 'CHIRPS v2.0', evidence: 'Monsoon precipitation of 1,420 mm/yr contributes to regional runoff.' },
  { name: 'Flow Accumulation', criterionId: 'flow_accumulation', weight: 0.1115, rawScore: 42.0, rating: 1.0, contribution: 0.1115, unit: 'cells', cls: 'positive', layerId: 'flow_accumulation', source: 'SRTM Flow Routing', evidence: 'Minimal upstream catchment area directly draining to ridge.' },
  { name: 'Drainage Density', criterionId: 'drainage_density', weight: 0.0668, rawScore: 1.2, rating: 2.0, contribution: 0.1336, unit: 'km/km²', cls: 'positive', layerId: 'drainage_density', source: 'Stream Network', evidence: 'Moderate stream density in immediate watershed.' },
  { name: 'Land Cover (LULC)', criterionId: 'lulc', weight: 0.0573, rawScore: 10.0, rating: 1.0, contribution: 0.0573, unit: 'class', cls: 'positive', layerId: 'lulc', source: 'ESA WorldCover', evidence: 'Dense tree canopy moderates runoff generation.' },
  { name: 'Elevation', criterionId: 'elevation', weight: 0.0345, rawScore: 1650.0, rating: 3.0, contribution: 0.1035, unit: 'm asl', cls: 'positive', layerId: 'elevation', source: 'SRTM DEM', evidence: 'Mountain elevation with gravity drainage.' },
  { name: 'Soil Texture', criterionId: 'soil', weight: 0.0317, rawScore: 2.0, rating: 2.0, contribution: 0.0635, unit: 'class', cls: 'positive', layerId: 'soil', source: 'SoilGrids v2.0', evidence: 'Coarse mountain soils provide moderate infiltration.' },
  { name: 'Curvature', criterionId: 'curvature', weight: 0.0282, rawScore: 0.005, rating: 2.0, contribution: 0.0564, unit: '1/m', cls: 'positive', layerId: 'curvature', source: 'SRTM DEM Derivatives', evidence: 'Convex ridge profile disperses runoff divergence.' },
  { name: 'NDVI Vegetation', criterionId: 'ndvi', weight: 0.0166, rawScore: 0.62, rating: 1.0, contribution: 0.0166, unit: 'index', cls: 'positive', layerId: 'ndvi', source: 'Sentinel-2 L2A', evidence: 'Vegetation cover provides canopy interception.' },
];

export const INITIAL_STATS = {
  model_id: 'flood_11_factor_v1',
  source_run_id: 56,
  scoring_mode: 'AVAILABLE_EVIDENCE_RENORMALIZED',
  crs: 'EPSG:4326',
  resolution_m: 30.0,
  total_pixels: 135148020,
  valid_pixels: 73000293,
  nodata_pixels: 62147727,
  valid_coverage_pct: 54.02,
  nodata_coverage_pct: 45.98,
  score_min: 1.063014,
  score_max: 4.869657,
  score_mean: 1.735700,
  score_std: 0.352100,
  class_distribution: [
    { class_value: 1, label: 'Very Low',  pixel_count: 46676143, percentage: 63.94, area_km2: 42008.53 },
    { class_value: 2, label: 'Low',       pixel_count: 24513495, percentage: 33.58, area_km2: 22062.15 },
    { class_value: 3, label: 'Moderate',  pixel_count: 1450815,  percentage: 1.99,  area_km2: 1305.73 },
    { class_value: 4, label: 'High',      pixel_count: 317406,   percentage: 0.43,  area_km2: 285.67 },
    { class_value: 5, label: 'Very High', pixel_count: 42434,    percentage: 0.06,  area_km2: 38.19 },
  ],
  evidence_distribution: [
    { criteria_count: 11, label: '11 / 11 Criteria (Full)', pixel_count: 49291505, percentage: 67.52 },
    { criteria_count: 10, label: '10 / 11 Criteria',        pixel_count: 23690551, percentage: 32.45 },
    { criteria_count: 9,  label: '9 / 11 Criteria',         pixel_count: 14347,    percentage: 0.02 },
    { criteria_count: 8,  label: '8 / 11 Criteria (Min)',   pixel_count: 3890,     percentage: 0.01 },
  ],
};

export const AI_PRESETS: Array<{ q: string; context?: string }> = [
  { q: 'Why is this location classified with its current flood susceptibility?', context: 'zone' },
  { q: 'What is the difference between Raw factor values and Standardized (1–5) ratings?', context: 'layer' },
  { q: 'What is Available-Evidence Renormalization mode vs Strict 11-of-11 mode?', context: 'model' },
  { q: 'What are the dominant flood risk factors in Himachal Pradesh?', context: 'model' },
  { q: 'Which criterion has the highest AHP weight in the Flood model?', context: 'model' },
  { q: 'What is the Consistency Ratio (CR) of this model?', context: 'model' },
];

export const AI_ANSWERS: Record<string, { text: string; actions?: Array<{ label: string; type: 'layer' | 'evidence' | 'stats'; target: string }> }> = {
  'Why is this location classified with its current flood susceptibility?': {
    text: `Under the canonical **11-Factor AHP Flood Model (Run #56)**, this location in Himachal Pradesh is evaluated using Available-Evidence multi-criteria synthesis:\n\n• **Slope (w=0.2306):** High gradient promotes rapid overland runoff away from ridges.\n• **Distance to Rivers (w=0.1480):** Proximity to active stream corridors dictates overbank inundation hazard.\n• **Rainfall (w=0.1326):** Monsoonal rainfall remains the dominant regional hazard driver.\n\nPixels with at least 8 valid criteria are dynamically renormalized, while pixels missing factors like soil are transparently flagged as Partial Evidence.`,
    actions: [
      { label: 'Show Slope Layer', type: 'layer', target: 'slope' },
      { label: 'Show Rainfall Layer', type: 'layer', target: 'rainfall' },
      { label: 'Show Classified Result', type: 'layer', target: 'flood_11_factor_v1_available_evidence_suitability_classified' },
    ],
  },
  'What is the difference between Raw factor values and Standardized (1–5) ratings?': {
    text: `• **Raw Factors** represent biophysical ground-truth measurements in original scientific units (e.g. Slope in degrees, Rainfall in mm/yr, Elevation in m asl, Distance to Rivers in meters).\n\n• **Standardized Ratings (1–5)** represent expert-graded vulnerability scores on a unified scale where 1 = Very Low Flood Susceptibility and 5 = Very High Flood Susceptibility.\n\nAHP multi-criteria weighted linear combination operates on these standardized 1–5 ratings.`,
    actions: [
      { label: 'View Rainfall Raw', type: 'layer', target: 'rainfall' },
      { label: 'View Rainfall Rating', type: 'layer', target: 'rainfall_rating' },
    ],
  },
  'What is Available-Evidence Renormalization mode vs Strict 11-of-11 mode?': {
    text: `• **Available-Evidence Renormalized Mode (Default):** Evaluates locations where at least 8 of the 11 criteria are valid. Weights of present criteria are renormalized to sum to 1.0, preserving continuous coverage across mountainous zones where certain remote sensing inputs (e.g. soil grids) have localized NoData.\n\n• **Strict 11-of-11 Mode:** Requires all 11 criteria to be simultaneously valid. Returns NoData wherever even a single factor is missing, serving as an audit and verification baseline.`,
    actions: [
      { label: 'Show Evidence Coverage', type: 'layer', target: 'flood_11_factor_v1_valid_criteria_count' },
      { label: 'Show Strict Result', type: 'layer', target: 'flood_11_factor_v1_strict_suitability_classified' },
    ],
  },
  'What are the dominant flood risk factors in Himachal Pradesh?': {
    text: `In the 11-factor AHP hierarchy, the three dominant contributors are:\n\n1. **Terrain Slope (23.06%):** Steep slopes force rapid runoff accumulation into valley bottoms.\n2. **Distance to Rivers (14.80%):** Flood vulnerability is concentrated within 500 m of mainstem river channels.\n3. **Topographic Wetness Index (14.22%):** Quantifies topographic moisture accumulation and surface ponding potential.\n4. **Annual Rainfall (13.26%):** Monsoonal cloudburst intensity triggers catastrophic peak discharges.`,
    actions: [
      { label: 'Inspect Model Weights', type: 'stats', target: 'metadata' },
    ],
  },
  'Which criterion has the highest AHP weight in the Flood model?': {
    text: `**Terrain Slope** has the highest priority eigenvalue weight at **0.230588 (23.06%)**, followed by **Distance to Rivers (14.80%)** and **TWI (14.22%)**. Together, terrain and hydrology account for over 65% of total flood hazard evaluation.`,
    actions: [
      { label: 'Show Slope Layer', type: 'layer', target: 'slope' },
    ],
  },
  'What is the Consistency Ratio (CR) of this model?': {
    text: `The Saaty Consistency Ratio (CR) for the 11-factor pairwise comparison matrix is **0.0158 (1.58%)**.\n\nSince this is well below the Saaty consistency threshold of **0.10 (10%)**, the decision matrix is mathematically consistent and validated. Principal eigenvalue λmax = 11.238, Random Index RI = 1.51.`,
    actions: [
      { label: 'View Model Metadata', type: 'stats', target: 'metadata' },
    ],
  },
};

export const LAYERS = INITIAL_LAYERS;
export const CRITERIA = INITIAL_CRITERIA;
export const ZONES = [INITIAL_ZONE];
export const CLASS_DIST = INITIAL_STATS.class_distribution;

